### ISSUE TITLE
Unparseable line "item2.X-ABLabel:"

### ISSUE THREAD

**Issue by tmerse** [scheibler/khard#70] opened 2016-06-08 08:49 UTC
A `.vcf`-file containing the line

`item2.X-ABLabel:`

will make khard crash with `string index out of range`.

**Comment by scheibler** [comment] 2016-06-08 09:33
Could you provide the whole crash log and the anonymized vcard please?

**Comment by tmerse** [comment] 2016-06-21 14:56
Sorry for this to take so long.

Here is the perpetrator:

 `6ff210e18faaac3e.vcf`

~~~
BEGIN:VCARD
VERSION:3.0
N:;Batman;;;
FN:Batman
REV:2016-06-09T12:48:49Z
UID:6ff210e18faaac3e
TEL;TYPE=CELL:+49123456777
TEL;TYPE=HOME,PREF:045-678-99999
item1.EMAIL;TYPE=PREF:BRUCE.WAYNE@imbatman.com
item2.EMAIL:BRUCE.WAYNE@gmail.com
item1.X-ABLabel:
item2.X-ABLabel:
END:VCARD
~~~

crash log:

~~~ {.bash}
$ khard
Address books: contacts, local
Traceback (most recent call last):
  File "/home/tobias/.local/bin/khard", line 11, in <module>
    sys.exit(main())
  File "/home/tobias/.local/lib/python2.7/site-packages/khard/khard.py", line 1353, in main
    list_subcommand(vcard_list)
  File "/home/tobias/.local/lib/python2.7/site-packages/khard/khard.py", line 762, in list_subcommand
    list_contacts(vcard_list)
  File "/home/tobias/.local/lib/python2.7/site-packages/khard/khard.py", line 315, in list_contacts
    key=lambda k: k[0].lower())[0]
  File "/home/tobias/.local/lib/python2.7/site-packages/khard/khard.py", line 315, in <lambda>
    key=lambda k: k[0].lower())[0]
IndexError: string index out of range
~~~

**Comment by tmerse** [comment] 2016-06-21 15:20
I slapped together this script in order to get a valid representation. Of course this is not an option in the long run.

~~~ {.bash}
rm -r ~/path/to/contacts/synced/sanitized
cp -r ~/path/to/contacts/synced/default ~/path/to/contacts/synced/sanitized

for file in ~/path/to/contacts/synced/sanitized/*
do
  sed -i '/X-ABLabel:/d' "$file"
done
~~~

**Comment by scheibler** [comment] 2016-06-23 08:08
The issue is fixed in the latest commit of the developer branch python3support. If you want to try,
you have to reinstall khard in a python3 environment first. A stable release will take some more
time.

item1.X-ABLabel is a custom label for the first email address. But cause it's empty, khard will
remove it during contact editing. The only type left then would be "pref" to indicate the preferred
email address. Don't know, why your contact program creates empty custom labels at all.

**Closed** 2016-07-18 07:54 UTC
