### ISSUE TITLE
Configure Merge Editor With Arguments

### ISSUE THREAD

**Issue by weilbith** [scheibler/khard#193] opened 2018-10-16 16:26 UTC
Hi.
I like to use _NeoVim_ for editing and merging. While _Vim_ brings its own command `vimdiff` for merging, _NeoVim_ use to call `nvim -d`. Unfortunately this seems not to be possible to define in the configuration file so far. I tried this way:
```bash
merge_editor = nvim -d
merge_editor = "nvim -d"
merge_editor = 'nvim -d'
```

Is this already possible and I tried it the wrong way or would it be possible to add this feature?

**Comment by lucc** [comment] 2018-10-17 15:22
This is a duplicate of #190. You are welcome to fix the docs so others learn this more easily :)

**Closed by lucc** 2018-10-17 15:22 UTC
